### ISSUE TITLE
UTF8 Support.

### ISSUE THREAD

**Issue by detmach** [rnielikki/IRCBot#2]
I am so sorry, I guess I couldn't explain it. There is no problem with the console screen.
IRC Chat Screen, etc. in Turkish. UTF8 does not read characters correctly. 
Image = https://i.imgyukle.com/2019/07/18/k8tMAt.png 
Sorry for bad english
Thanks

**Comment by rnielikki** [comment]
If clients' encoding doesn't match, it looks differently. Possibly your client's(sender's) encoding is other than UTF-8. Even some servers 'recommend' to use specific encoding, there're no rules which encoding must be used in standard, so you can do either:
1. Change the sender's(the client where you typed manually) encoding
2. You can change the bot's encoding
In case of 2, currently this client doesn't support encoding, so you can edit from Program.cs manually and recompile:
https://github.com/rnielikki/IRCBot/blob/6f2b7a5500969b2c9b20d61eef8a2ce850ed392e/IRCBot/Program.cs#L11
Encoding option will be added in the other version, so it'll not fixed in here. Sorry for inconvenience.
