### ISSUE TITLE
Multiple Command Prefix

### ISSUE THREAD

**Issue by detmach** [rnielikki/IRCBot#3]
IRCBot.cs 157 :  if (Value[3][1] == setting.CommandPrefix) 
Change :  if (setting.CommandPrefix.Contains(Value[3][1]))

Setting.cs 167  : s.CommandPrefix = S["CommandPrefix"]?.Value[0] ?? (++nulled).ToString()[0];
Change : s.CommandPrefix = S["CommandPrefix"]?.Value ?? (++nulled).ToString();

Setting.cs 234 : public char CommandPrefix { get; internal set; } = '\0';
Change :  public string CommandPrefix { get; internal set; } = "!";

This can be used for multiple prefixes.

Thanks.

**Comment by rnielikki** [comment]
Personally, I don't know why multiple prefix is needed, other than "for public(to channel) and private message". In my opinion, multiple prefixes make confusing and thus each bot should have unique prefix. If I'm wrong, please explain why it's really needed.

And if you can edit the code, please use pull request.

**Comment by detmach** [comment]
Fully Option Related. We (the Developer) make the job easier
If you want one, you can use multiple prefixes. Does this pose a problem for us?

Thanks

**Comment by rnielikki** [comment]
Developer doesn't need to fulfill every requests, sometimes features make program nasty and more difficult to use. I know that's not a big issue here, but this will not be added, because I don't want it. You can make branch and continue contributing.
And this repo will not add any feature, no updates except bugs, (The reason is now available in the [README.md file](https://github.com/rnielikki/IRCBot/blob/master/README.md))

This discussion will be closed.
